[package]
name = "keyswitch"
version = "0.1.0"
authors = ["Michael Hadley <mikethadley@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
input-linux = "0.3.0"
libc = "0.2"
linked_hash_set = "0.1.4"
